sudo: required
services:
  - docker

before_install:
  - docker build -t albertvdm/ui-dev -f ./ui/Dockerfile.dev ./ui

scripts:
  - docker run albertvdm/ui-dev npm run test --coverage --forceExit

after_success:
  - docker build -t albertvdm/ui-prod -f ./ui/Dockerfile ./ui
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push albertvdm/ui-prod
