sudo: required
services:
  - docker

before_install:
  - docker build -t albertvdm/ui -f ./ui/Dockerfile.dev ./ui

scripts:
  - docker run -t albertvdm/ui npm run tests -- --coverage

#Login to docker and push

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push albertvdm/ui
