sudo: required
services:
  - docker

before_install:
  - docker build -t albertvdm/ui -f Dockerfile.dev ./ui

scripts:
  - docker run albertvdm/ui npm run tests -- --coverage

#Login to docker and push

 # after_success:
