version: '3'  
services:
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui/package.json:/app/package.json
      - ./ui/src:/app/src
    ports:
      - 3000:3000


